version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    tty: true
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-app
    working_dir: /usr/src/app
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    tty: true
volumes:
  redis_data: