version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./certs/cert.key:/etc/ssl/private/cert.key
    depends_on:
      - app
    tty: true
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    tty: true
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    tty: true
volumes:
  redis_data: