version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: infotech_auto_attendance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tty: true

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    tty: true
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    tty: true
volumes:
  postgres_data:
  redis_data: